"""
DWG/DXF file importer - generates XML content for Read DWG/DXF Data command
"""
from typing import List
from .utils import normalize_file_path


def generate_dwg_xml_content(file_path: str, PrePostfixForModels: str) -> List[str]:
    """
    Generate XML content for DWG files
    
    Args:
        file_path: Full path to the DWG file
        PrePostfixForModels: Pre*postfix for model names
        
    Returns:
        List of XML lines for the DWG import command
    """
    xml_content = []
    
    xml_content.append('      <Run_option>')
    xml_content.append('        <Name>Read DWG/DXF Data</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <SLF_data>')
    xml_content.append('          <screen_layout>')
    xml_content.append('            <version>1.0</version>')
    xml_content.append('            <panel>')
    xml_content.append('              <name>Read DWG/DXF Data</name>')
    xml_content.append('              <x>138</x>')
    xml_content.append('              <y>208</y>')
    xml_content.append('              <resize>')
    xml_content.append('                <width>2.0735786</width>')
    xml_content.append('                <height>1</height>')
    xml_content.append('              </resize>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Create anonymous function</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Import method</name>')
    xml_content.append('                <value/>')
    xml_content.append('              </input_box>')
    xml_content.append('              <file_box>')
    xml_content.append('                <name>File</name>')
    formatted_path = normalize_file_path(file_path).replace('\\', '/')
    xml_content.append(f'                <value>{formatted_path}</value>')
    xml_content.append('              </file_box>')
    xml_content.append('              <file_box>')
    xml_content.append('                <name>Map file</name>')
    xml_content.append('                <value/>')
    xml_content.append('              </file_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Pre*postfix for models</name>')
    xml_content.append(f'                <value>{PrePostfixForModels}</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Allow merge into existing models</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Target layer</name>')
    xml_content.append('                <value/>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Null level value</name>')
    xml_content.append('                <value>0</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Default lineweight</name>')
    xml_content.append('                <value>0.25</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Spline approximation</name>')
    xml_content.append('                <value>12</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Names</name>')
    xml_content.append('                <value>layer for name</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Images</name>')
    xml_content.append('                <value>ignore</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Blocks</name>')
    xml_content.append('                <value>to symbols</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Block attributes</name>')
    xml_content.append('                <value>ignore</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Only create visible symbols</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Translate 3DFaces to Faces</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Use 12d Acad colour numbers</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Create 2d/3d polys from ctrl points</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Head to tail points/lines</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Only load visible layers</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Load paper space</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Load xref files</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <run_button>')
    xml_content.append('                <name>&amp;Read</name>')
    xml_content.append('              </run_button>')
    xml_content.append('            </panel>')
    xml_content.append('          </screen_layout>')
    xml_content.append('        </SLF_data>')
    xml_content.append('        <Parameter_Mappings>')
    xml_content.append('        </Parameter_Mappings>')
    xml_content.append('      </Run_option>')
    
    return xml_content

