"""
IFC file importer - generates XML content for IFC Express Reader command
"""
from typing import List
from .utils import normalize_file_path


def generate_ifc_xml_content(actual_file_path: str, modified_variable: str) -> List[str]:
    """
    Generate XML content for IFC files
    
    Args:
        actual_file_path: Full path to the IFC file
        modified_variable: Variable name for the model
        
    Returns:
        List of XML lines for the IFC import command
    """
    xml_content = []
    
    xml_content.append('      <Run_option>')
    xml_content.append('        <Name>IFC Express Reader</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append(f'        <Comment>import {modified_variable}</Comment>')
    xml_content.append('        </Comments>')
    xml_content.append('        <SLF_data>')
    xml_content.append('          <screen_layout>')
    xml_content.append('            <version>1.0</version>')
    xml_content.append('            <panel>')
    xml_content.append('              <name>IFC Express Reader</name>')
    xml_content.append('              <x>159</x>')
    xml_content.append('              <y>352</y>')
    xml_content.append('              <resize>')
    xml_content.append('                <width>1.9449541</width>')
    xml_content.append('                <height>1</height>')
    xml_content.append('              </resize>')
    xml_content.append('              <widget_pages>')
    xml_content.append('                <name>Tab box</name>')
    xml_content.append('                <current_page>General</current_page>')
    xml_content.append('                <widget_page>')
    xml_content.append('                  <name>General</name>')
    xml_content.append('                  <files_box>')
    xml_content.append('                    <name>Input file</name>')
    xml_content.append('                    <tick_box>')
    xml_content.append('                      <name>Advanced</name>')
    xml_content.append('                      <value>false</value>')
    xml_content.append('                    </tick_box>')
    xml_content.append('                    <widget_pages>')
    xml_content.append('                      <name>Pages</name>')
    xml_content.append('                      <current_page>1</current_page>')
    xml_content.append('                      <widget_page>')
    xml_content.append('                        <name>1</name>')
    xml_content.append('                        <file_box>')
    xml_content.append('                          <name>File to read</name>')
    formatted_path = normalize_file_path(actual_file_path).replace('/', '\\')
    xml_content.append(f'                          <value>{formatted_path}</value>')
    xml_content.append('                        </file_box>')
    xml_content.append('                      </widget_page>')
    xml_content.append('                    </widget_pages>')
    xml_content.append('                  </files_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Model</name>')
    xml_content.append(f'                    <value>{modified_variable} ifc</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Pre*postfix for models</name>')
    xml_content.append(f'                    <value>{modified_variable}/*</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Split data into Entity models?</name>')
    xml_content.append('                    <value>true</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Presentation Layer as model</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Use pre*postfix for tins</name>')
    xml_content.append('                    <value>true</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Clean model?</name>')
    xml_content.append('                    <value>true</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Apply map coordinates</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Use reference trimeshes</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Save ifc file in memory?</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Null level value</name>')
    xml_content.append('                    <value>0</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Make string name</name>')
    xml_content.append('                    <value>Instance name</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Pit pipe mode</name>')
    xml_content.append('                    <value>Trimeshes</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Default colour</name>')
    xml_content.append('                    <value>cyan</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Save GlobalId as Attribute?</name>')
    xml_content.append('                    <value>true</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>GlobalId attribute path</name>')
    xml_content.append('                    <value>IfcGlobalId</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Save Element Type as Attribute?</name>')
    xml_content.append('                    <value>true</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Element Type attribute path</name>')
    xml_content.append('                    <value>IfcEntity</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                </widget_page>')
    xml_content.append('                <widget_page>')
    xml_content.append('                  <name>Alignment</name>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Reverse calc parts</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <tick_box>')
    xml_content.append('                    <name>Copy alignment</name>')
    xml_content.append('                    <value>false</value>')
    xml_content.append('                  </tick_box>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Label style</name>')
    xml_content.append('                    <value>default</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                </widget_page>')
    xml_content.append('                <widget_page>')
    xml_content.append('                  <name>Unit</name>')
    xml_content.append('                  <input_box>')
    xml_content.append('                    <name>Convert length unit to</name>')
    xml_content.append('                    <value>METRE</value>')
    xml_content.append('                  </input_box>')
    xml_content.append('                </widget_page>')
    xml_content.append('              </widget_pages>')
    xml_content.append('              <run_button>')
    xml_content.append('                <name>Read</name>')
    xml_content.append('              </run_button>')
    xml_content.append('            </panel>')
    xml_content.append('          </screen_layout>')
    xml_content.append('        </SLF_data>')
    xml_content.append('        <Parameter_Mappings>')
    xml_content.append('        </Parameter_Mappings>')
    xml_content.append('      </Run_option>')
    
    return xml_content

