"""
Generate Explode Trimeshes command
"""
from typing import List


def explode_trimesh_command(model_name: str) -> List[str]:
    """
    Generate Explode Trimeshes command. Explodes trimeshes in a model then copies the result back into itself.
    
    Args:
        model_name: Model name to use for the explode trimeshes command
    
    Returns:
        List of XML lines for Explode Trimeshes command
    """
    return [
        '      <Run_option>',
        '        <Name>Explode Trimeshes</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '        <SLF_data>',
        '          <screen_layout>',
        '            <version>1.0</version>',
        '            <panel>',
        '              <name>Explode Trimeshes</name>',
        '              <x>561</x>',
        '              <y>325</y>',
        '              <source_box>',
        '                <name>Data source of trimeshes to explode</name>',
        '                <mode>Source_Box_Filter</mode>',
        '                <widget_pages>',
        '                  <name>Data source of trimeshes to explode - Groups</name>',
        '                  <current_page>String Info</current_page>',
        '                  <widget_page>',
        '                    <name>View</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - View Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model</name>',
        '                                        <input_box>',
                    f'                      <name>Data source of trimeshes to explode - Model Name</name>',
                    f'                      <value>{model_name}</value>',
                    '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Model ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Model ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Models</name>',
        '                    <grid_box>',
        '                      <name>Models</name>',
        '                      <columns>',
        '                        <column>Model</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>String Info</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Type</name>',
        '                      <value>3d primitive all</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Colour</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Breakline</name>',
        '                      <value>any string</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Linestyle</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - String Weight</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Point ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Point ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Point ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Polygons</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Fence Mode</name>',
        '                      <value>String inside</value>',
        '                    </input_box>',
        '                    <polygon_box>',
        '                      <name>Data source of trimeshes to explode - Fence Polygon</name>',
        '                    </polygon_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Extents</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element X Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Y Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Z Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element X Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Y Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Z Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Plan length</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Plan Length Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Plan Length Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Function</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Function Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Function ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Function ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Time</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Create Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Create Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Update Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Element Update Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model Attributes</name>',
        '                    <grid_box>',
        '                      <name>Model Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Element Attributes</name>',
        '                    <grid_box>',
        '                      <name>Element Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Attributes</name>',
        '                    <grid_box>',
        '                      <name>Vertex Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment Attributes</name>',
        '                    <grid_box>',
        '                      <name>Segment Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Count</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Vertex Count Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Vertex Count Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Tags</name>',
        '                    <input_box>',
        '                      <name>Tag</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Search mode</name>',
        '                      <value>String and models tags</value>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Name masks</name>',
        '                    <grid_box>',
        '                      <name>Name mask filter</name>',
        '                      <columns>',
        '                        <column>Active?</column>',
        '                        <column>Not?</column>',
        '                        <column>Name Mask</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Vertex UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Vertex UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Segment UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data source of trimeshes to explode - Segment UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                </widget_pages>',
        '                <tick_box>',
        '                  <name>Use log lines</name>',
        '                  <value>false</value>',
        '                </tick_box>',
        '              </source_box>',
        '              <tick_box>',
        '                <name>Polymesh face</name>',
        '                <value>false</value>',
        '              </tick_box>',
        '              <tick_box>',
        '                <name>Solid fill string</name>',
        '                <value>true</value>',
        '              </tick_box>',
        '              <input_box>',
        '                <name>Fill blend</name>',
        '                <value>1</value>',
        '              </input_box>',
        '                            <input_box>',
              f'                <name>Output model</name>',
              f'                <value>{model_name}</value>',
              '              </input_box>',
        '              <run_button>',
        '                <name>Explode</name>',
        '              </run_button>',
        '            </panel>',
        '          </screen_layout>',
        '        </SLF_data>',
        '        <record_name>Explode Trimeshes</record_name>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Run_option>',
    ]