"""
Generate Filter delete trimesh command
"""
from typing import List

def filter_delete_trimesh_command(model_name: str) -> List[str]:
    """
    Generate Filter delete trimesh command. Deletes trimeshes out of a model.
    
    Args:
        model_name: Model name to use for the filter delete trimesh command
    
    Returns:
        List of XML lines for Filter delete trimesh command
    """
    return [
        '      <Run_option>',
        '        <Name>Delete trimesh</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>true</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '        <SLF_data>',
        '          <screen_layout>',
        '            <version>1.0</version>',
        '            <panel>',
        '              <name>Delete</name>',
        '              <x>435</x>',
        '              <y>636</y>',
        '              <source_box>',
        '                <name>Data to delete</name>',
        '                <mode>Source_Box_Filter</mode>',
        '                <tick_box>',
        '                  <name>Data to delete - Vertex Processing</name>',
        '                  <value>false</value>',
        '                </tick_box>',
        '                <widget_pages>',
        '                  <name>Data to delete - Groups</name>',
        '                  <current_page>String Info</current_page>',
        '                  <widget_page>',
        '                    <name>View</name>',
        '                    <input_box>',
        '                      <name>Data to delete - View Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Model Name</name>',
        f'                      <value>{model_name}</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Model ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Model ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Models</name>',
        '                    <grid_box>',
        '                      <name>Models</name>',
        '                      <columns>',
        '                        <column>Model</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>String Info</name>',
        '                    <input_box>',
        '                      <name>Data to delete - String Type</name>',
        '                      <value>3d primitive all</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - String Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - String Colour</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - String Breakline</name>',
        '                      <value>any string</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - String Linestyle</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - String Weight</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Point ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Point ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Point ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Polygons</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Fence Mode</name>',
        '                      <value>String inside</value>',
        '                    </input_box>',
        '                    <polygon_box>',
        '                      <name>Data to delete - Fence Polygon</name>',
        '                    </polygon_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Extents</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Element X Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Y Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Z Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element X Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Y Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Z Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Plan length</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Plan Length Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Plan Length Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Element ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Function</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Function Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Function ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Function ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Time</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Create Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Create Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Update Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Element Update Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model Attributes</name>',
        '                    <grid_box>',
        '                      <name>Model Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Element Attributes</name>',
        '                    <grid_box>',
        '                      <name>Element Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Attributes</name>',
        '                    <grid_box>',
        '                      <name>Vertex Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment Attributes</name>',
        '                    <grid_box>',
        '                      <name>Segment Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Count</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Vertex Count Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Vertex Count Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Tags</name>',
        '                    <input_box>',
        '                      <name>Tag</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Search mode</name>',
        '                      <value>String and models tags</value>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Name masks</name>',
        '                    <grid_box>',
        '                      <name>Name mask filter</name>',
        '                      <columns>',
        '                        <column>Active?</column>',
        '                        <column>Not?</column>',
        '                        <column>Name Mask</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Vertex UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Vertex UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to delete - Segment UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to delete - Segment UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                </widget_pages>',
        '                <tick_box>',
        '                  <name>Use log lines</name>',
        '                  <value>false</value>',
        '                </tick_box>',
        '              </source_box>',
        '              <input_box>',
        '                <name>Delete mode</name>',
        '                <value>Split</value>',
        '              </input_box>',
        '              <target_box>',
        '                <name>Target</name>',
        '                <mode>Target_Box_Copy_To_One_Model</mode>',
        '                <input_box>',
        '                  <name>Target - Copy to model</name>',
        '                  <value/>',
        '                </input_box>',
        '              </target_box>',
        '              <run_button>',
        '                <name>Delete</name>',
        '              </run_button>',
        '            </panel>',
        '          </screen_layout>',
        '        </SLF_data>',
        '        <record_name>Delete</record_name>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Run_option>',
    ]