"""
Generate Create Contour Smooth Label command
"""
from typing import List


def create_contour_smooth_label_command(prefix: str, cell_value: str) -> List[str]:
    """
    Generate Create Contour Smooth Label XML command
    
    Args:
        prefix: Prefix for the model
        cell_value: Cell value for naming
    
    Returns:
        List of XML lines for Create Contour Smooth Label command
    """
    return [
        '      <Manual_option>',
        f'        <Name>{cell_value} tin Contours Function</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '        <Panel_Data><screen_layout>',
        '  <version>1.0</version>',
        '  <panel>',
        '    <name>Tin: Contour, Smooth and Label</name>',
        '    <x>957</x>',
        '    <y>606</y>',
        '    <input_box>',
        '      <name>Function name</name>',
        f'      <value>{cell_value} tin Contours</value>',
        '    </input_box>',
        '    <input_box>',
        '      <name>Tin to contour</name>',
        f'      <value>tin {cell_value} wIntRoad</value>',
        '    </input_box>',
        '    <widget_pages>',
        '      <name>Mode</name>',
        '      <current_page>Contours</current_page>',
        '      <widget_page>',
        '        <name>Contours</name>',
        '        <input_box>',
        '          <name>Model for contours</name>',
        f'          <value>{prefix}/{cell_value} Contours</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Contour increment</name>',
        '          <value>0.2</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Name</name>',
        '          <value>CNT MINOR</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Colour</name>',
        '          <value>pen 025a</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Linestyle</name>',
        '          <value>DASHED</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Weight</name>',
        '          <value />',
        '        </input_box>',
        '        <tick_box>',
        '          <name>Smooth contours</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Preserve string points</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '      </widget_page>',
        '      <widget_page>',
        '        <name>Major Contours</name>',
        '        <tick_box>',
        '          <name>Create major contours</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <input_box>',
        '          <name>Model for major contours</name>',
        '          <value />',
        '        </input_box>',
        '        <input_box>',
        '          <name>Major contour increment</name>',
        '          <value>1</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Name</name>',
        '          <value>CNT MAJOR</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Colour</name>',
        '          <value>pen 035a</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Linestyle</name>',
        '          <value>1</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Weight</name>',
        '          <value />',
        '        </input_box>',
        '      </widget_page>',
        '      <widget_page>',
        '        <name>Range</name>',
        '        <input_box>',
        '          <name>Contour minimum</name>',
        '          <value />',
        '        </input_box>',
        '        <input_box>',
        '          <name>Contour maximum</name>',
        '          <value />',
        '        </input_box>',
        '        <input_box>',
        '          <name>Contour reference</name>',
        '          <value>0</value>',
        '        </input_box>',
        '        <tick_box>',
        '          <name>Colour by range</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <file_box>',
        '          <name>Height range file</name>',
        '          <value />',
        '        </file_box>',
        '        <tick_box>',
        '          <name>Interpolate colours</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Colour text labels</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '      </widget_page>',
        '      <widget_page>',
        '        <name>Labels</name>',
        '        <tick_box>',
        '          <name>Label contours</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Label major contours only</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <input_box>',
        '          <name>Model for labels</name>',
        f'          <value>{prefix}/{cell_value} Contour Labels</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Label method</name>',
        '          <value>Centred line facing up hill</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Decimal places</name>',
        '          <value>1</value>',
        '        </input_box>',
        '        <textstyle_data_box>',
        '          <name>Textstyle data</name>',
        '          <value>',
        '            <textstyle>ISOCP</textstyle>',
        '            <name>CNT LABEL</name>',
        '            <type>world</type>',
        '            <size>1.2</size>',
        '            <angle>0</angle>',
        '            <x_factor>1</x_factor>',
        '            <slant>0</slant>',
        '            <offset>0</offset>',
        '            <raise>0</raise>',
        '            <colour>acad 007</colour>',
        '            <whiteout>no_colour</whiteout>',
        '            <border>no_colour</border>',
        '            <justify>middle-centre</justify>',
        '            <ttf_underline>false</ttf_underline>',
        '            <ttf_strikeout>false</ttf_strikeout>',
        '            <ttf_italic>false</ttf_italic>',
        '            <ttf_outline>false</ttf_outline>',
        '            <ttf_weight>400</ttf_weight>',
        '          </value>',
        '        </textstyle_data_box>',
        '        <input_box>',
        '          <name>Start dist (w)</name>',
        '          <value>50</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Separation (w)</name>',
        '          <value>250</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Model of label lines</name>',
        '          <value></value>',
        '        </input_box>',
        '        <tick_box>',
        '          <name>Label start and end</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '      </widget_page>',
        '    </widget_pages>',
        '    <run_button>',
        '      <name>Process</name>',
        '    </run_button>',
        '  </panel>',
        '</screen_layout>',
        '</Panel_Data>',
        '        <Panel_Name>Tin: Contour, Smooth and Label</Panel_Name>',
        '        <Clean_Up>1</Clean_Up>',
        '        <Buttons>',
        '          <Button>',
        '            <Name> Process </Name>',
        '            <Order>0</Order>',
        '          </Button>',
        '        </Buttons>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Manual_option>'
    ]
