"""
Generate Drape to TIN command
"""
from typing import List


def drape_strings_to_tin_command(data_to_drape: str, z_offset: str, tin_name: str) -> List[str]:
    """
    Generate Drape to TIN XML command
    
    Args:
        data_to_drape: Data to drape
        z_offset: Z offset
        tin_name: Name of the TIN to drape to
    
    Returns:
        List of XML lines for Drape to TIN command
    """
    return [
        '      <Run_option>',
        '        <Name>Drape to survey tin</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '        <SLF_data>',
        '          <screen_layout>',
        '            <version>1.0</version>',
        '            <panel>',
        '              <name>Drape</name>',
        '              <x>631</x>',
        '              <y>360</y>',
        '              <source_box>',
        '                <name>Data to drape</name>',
        '                <mode>Source_Box_Models</mode>',
        '                <grid_box>',
        '                  <name>Models</name>',
        '                  <columns>',
        '                    <column>Model</column>',
        '                  </columns>',
        '                  <data>',
        '                    <r>',
        f'                      <c>{data_to_drape}</c>',
        '                    </r>',
        '                  </data>',
        '                </grid_box>',
        '              </source_box>',
        '              <input_box>',
        '                <name>Tin</name>',
        f'                <value>{tin_name}</value>',
        '              </input_box>',
        '              <input_box>',
        '                <name>Drape Mode</name>',
        '                <value>Vertices Only</value>',
        '              </input_box>',
        '              <input_box>',
        '                <name>Z offset</name>',
        f'                <value>{z_offset}</value>',
        '              </input_box>',
        '              <widget_pages>',
        '                <name>Drape Mode Pages</name>',
        '                <current_page>Vertices</current_page>',
        '                <widget_page>',
        '                  <name>Normal</name>',
        '                  <tick_box>',
        '                    <name>Produce faces</name>',
        '                    <value>false</value>',
        '                  </tick_box>',
        '                  <tick_box>',
        '                    <name>Keep source linetyles</name>',
        '                    <value>true</value>',
        '                  </tick_box>',
        '                  <tick_box>',
        '                    <name>Colour draped string by tin</name>',
        '                    <value>false</value>',
        '                  </tick_box>',
        '                </widget_page>',
        '                <widget_page>',
        '                  <name>Vertices</name>',
        '                  <input_box>',
        '                    <name>End points tolerance</name>',
        '                    <value />',
        '                  </input_box>',
        '                  <tick_box>',
        '                    <name>Skip 2d strings</name>',
        '                    <value>true</value>',
        '                  </tick_box>',
        '                  <tick_box>',
        '                    <name>Pass other strings</name>',
        '                    <value>true</value>',
        '                  </tick_box>',
        '                  <tick_box>',
        '                    <name>Only drape null Z-values</name>',
        '                    <value>false</value>',
        '                  </tick_box>',
        '                </widget_page>',
        '              </widget_pages>',
        '              <target_box>',
        '                <name>Target</name>',
        '                <mode>Target_Box_Move_To_Original_Model</mode>',
        '                <tick_box>',
        '                  <name>Target - Replace existing data</name>',
        '                  <value>true</value>',
        '                </tick_box>',
        '              </target_box>',
        '              <run_button>',
        '                <name>&amp;Drape</name>',
        '              </run_button>',
        '            </panel>',
        '          </screen_layout>',
        '        </SLF_data>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Run_option>'
    ]
