"""
Generate Triangulate Manual_option command
"""
from typing import List


def triangulate_manual_option_command(
    modified_variable: str,
    prefix: str,
    surface_value: str,
    file_ext: str,
    options_ext: str,
    discipline: str,
    continue_on_failure: bool = True,
    comments: str = ""
) -> List[str]:
    failure_str = 'true' if continue_on_failure else 'false'
    """
    Generate Triangulate a Data Source Manual_option XML command
    
    Args:
        modified_variable: View name (variable with spaces instead of hyphens)
        prefix: Prefix name
        surface_value: Surface value (description)
        file_ext: File extension
        options_ext: Options extension (e.g., "Opt 01", "Opt 02", or empty)
        discipline: Discipline name
    
    Returns:
        List of XML lines for Triangulate Manual_option command
    """
    return [
        '      <Label>',
        '        <Name>create new tin</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '      </Label>',
        '      <Manual_option>',
        '        <Name>Option Triangulate a Data Source - Manual</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        f'          {comments}',
        '        </Comments>',
        '        <Panel_Data><screen_layout>',
        '  <version>1.0</version>',
        '  <panel>',
        '    <name>Triangulate a Data Source</name>',
        '    <x>458</x>',
        '    <y>287</y>',
        '    <widget_pages>',
        '      <name>Tabs</name>',
        '      <current_page>General</current_page>',
        '      <widget_page>',
        '        <name>General</name>',
        '        <input_box>',
        '          <name>Retriangulate function</name>',
        f'          <value>{modified_variable} tin</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>New tin name</name>',
        f'          <value>tin {prefix} {surface_value} {file_ext} {options_ext}</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Tin colour</name>',
        '          <value>vis granular2</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Tin style</name>',
        '          <value>1</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Model for tin</name>',
        f'          <value>tin/{discipline}/{prefix} {surface_value} {file_ext} {options_ext}</value>',
        '        </input_box>',
        '        <tick_box>',
        '          <name>Preserve strings</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Weed tin</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Cell method</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Remove bubbles</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Triangle data</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Colour by triangle data</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '        <tick_box>',
        '          <name>Create many</name>',
        '          <value>false</value>',
        '        </tick_box>',
        '      </widget_page>',
        '      <widget_page>',
        '        <name>Data</name>',
        '        <source_box>',
        '          <name>Data to triangulate</name>',
        '          <mode>Source_Box_View</mode>',
        '          <input_box>',
        '            <name>Data to triangulate - View</name>',
        f'            <value>{modified_variable}</value>',
        '          </input_box>',
        '        </source_box>',
        '        <polygon_box>',
        '          <name>Data polygon</name>',
        '        </polygon_box>',
        '      </widget_page>',
        '      <widget_page>',
        '        <name>Nulling</name>',
        '        <tick_box>',
        '          <name>Apply nulling</name>',
        '          <value>true</value>',
        '        </tick_box>',
        '        <input_box>',
        '          <name>Angle</name>',
        '          <value>5</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Length</name>',
        '          <value>5</value>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Combined angle</name>',
        '          <value/>',
        '        </input_box>',
        '        <input_box>',
        '          <name>Combined length</name>',
        '          <value/>',
        '        </input_box>',
        '        <polygon_box>',
        '          <name>Null polygon</name>',
        '        </polygon_box>',
        '      </widget_page>',
        '    </widget_pages>',
        '    <run_button>',
        '      <name>Triangulate</name>',
        '    </run_button>',
        '  </panel>',
        '</screen_layout></Panel_Data>',
        '        <Panel_Name>Triangulate a Data Source</Panel_Name>',
        '        <Clean_Up>1</Clean_Up>',
        '        <Buttons>',
        '          <Button>',
        '            <Name>Triangulate</Name>',
        '            <Order>0</Order>',
        '          </Button>',
        '        </Buttons>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Manual_option>'
    ]



