def generate_apply_attr_xml_content(view):
    """
    Generate XML content for Apply Attribute Manipulator files
    """
    xml_content = []
      
    xml_content.append('      <Run_option>')
    xml_content.append('        <Name>Apply Attribute ModelNameToStringAttr</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <SLF_data>')
    xml_content.append('          <screen_layout>')
    xml_content.append('            <version>1.0</version>')
    xml_content.append('            <panel>')
    xml_content.append('              <name>Apply Attribute Manipulator File</name>')
    xml_content.append('              <x>715</x>')
    xml_content.append('              <y>55</y>')
    xml_content.append('              <source_box>')
    xml_content.append('                <name>Data to manipulate</name>')
    xml_content.append('                <mode>Source_Box_View</mode>')
    xml_content.append('                <input_box>')
    xml_content.append('                  <name>Data to manipulate - View</name>')
    xml_content.append(f'                  <value>{view}</value>')
    xml_content.append('                </input_box>')
    xml_content.append('              </source_box>')
    xml_content.append('              <file_box>')
    xml_content.append('                <name>Attribute manipulator file</name>')
    xml_content.append('                <value>ModelNameToStringAttr.12dattmf</value>')
    xml_content.append('              </file_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Manipulate direction</name>')
    xml_content.append('                <value>Forward</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Delete Attribute to Use</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>One-many manipulating mode</name>')
    xml_content.append('                <value>Ignored</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Print debug messages</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <target_box>')
    xml_content.append('                <name>Target</name>')
    xml_content.append('                <mode>Target_Box_Move_To_Original_Model</mode>')
    xml_content.append('                <tick_box>')
    xml_content.append('                  <name>Target - Replace existing data</name>')
    xml_content.append('                  <value>true</value>')
    xml_content.append('                </tick_box>')
    xml_content.append('              </target_box>')
    xml_content.append('              <run_button>')
    xml_content.append('                <name>Apply</name>')
    xml_content.append('              </run_button>')
    xml_content.append('            </panel>')
    xml_content.append('          </screen_layout>')
    xml_content.append('        </SLF_data>')
    xml_content.append('        <record_name>Apply Attribute Manipulator File</record_name>')
    xml_content.append('        <Parameter_Mappings>')
    xml_content.append('        </Parameter_Mappings>')
    xml_content.append('      </Run_option>')
    xml_content.append('      <Run_option>')
    xml_content.append('        <Name>Apply Attribute StringAttrDeconcat</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <SLF_data>')
    xml_content.append('          <screen_layout>')
    xml_content.append('            <version>1.0</version>')
    xml_content.append('            <panel>')
    xml_content.append('              <name>Apply Attribute Manipulator File</name>')
    xml_content.append('              <x>1058</x>')
    xml_content.append('              <y>47</y>')
    xml_content.append('              <source_box>')
    xml_content.append('                <name>Data to manipulate</name>')
    xml_content.append('                <mode>Source_Box_View</mode>')
    xml_content.append('                <input_box>')
    xml_content.append('                  <name>Data to manipulate - View</name>')
    xml_content.append(f'                  <value>{view}</value>')
    xml_content.append('                </input_box>')
    xml_content.append('              </source_box>')
    xml_content.append('              <file_box>')
    xml_content.append('                <name>Attribute manipulator file</name>')
    xml_content.append('                <value>StringAttrDeconcat.12dattmf</value>')
    xml_content.append('              </file_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Manipulate direction</name>')
    xml_content.append('                <value>Forward</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Delete Attribute to Use</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>One-many manipulating mode</name>')
    xml_content.append('                <value>Ignored</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Print debug messages</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <target_box>')
    xml_content.append('                <name>Target</name>')
    xml_content.append('                <mode>Target_Box_Move_To_Original_Model</mode>')
    xml_content.append('                <tick_box>')
    xml_content.append('                  <name>Target - Replace existing data</name>')
    xml_content.append('                  <value>true</value>')
    xml_content.append('                </tick_box>')
    xml_content.append('              </target_box>')
    xml_content.append('              <run_button>')
    xml_content.append('                <name>Apply</name>')
    xml_content.append('              </run_button>')
    xml_content.append('            </panel>')
    xml_content.append('          </screen_layout>')
    xml_content.append('        </SLF_data>')
    xml_content.append('        <record_name>Apply Attribute Manipulator File</record_name>')
    xml_content.append('        <Parameter_Mappings>')
    xml_content.append('        </Parameter_Mappings>')
    xml_content.append('      </Run_option>')
    xml_content.append('      <Run_option>')
    xml_content.append('        <Name>Apply Attribute ModelAttrNameToStringName</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <SLF_data>')
    xml_content.append('          <screen_layout>')
    xml_content.append('            <version>1.0</version>')
    xml_content.append('            <panel>')
    xml_content.append('              <name>Apply Attribute Manipulator File</name>')
    xml_content.append('              <x>1416</x>')
    xml_content.append('              <y>47</y>')
    xml_content.append('              <source_box>')
    xml_content.append('                <name>Data to manipulate</name>')
    xml_content.append('                <mode>Source_Box_View</mode>')
    xml_content.append('                <input_box>')
    xml_content.append('                  <name>Data to manipulate - View</name>')
    xml_content.append(f'                  <value>{view}</value>')
    xml_content.append('                </input_box>')
    xml_content.append('              </source_box>')
    xml_content.append('              <file_box>')
    xml_content.append('                <name>Attribute manipulator file</name>')
    xml_content.append('                <value>ModelAttrNameToStringName.12dattmf</value>')
    xml_content.append('              </file_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>Manipulate direction</name>')
    xml_content.append('                <value>Forward</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Delete Attribute to Use</name>')
    xml_content.append('                <value>false</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <input_box>')
    xml_content.append('                <name>One-many manipulating mode</name>')
    xml_content.append('                <value>Ignored</value>')
    xml_content.append('              </input_box>')
    xml_content.append('              <tick_box>')
    xml_content.append('                <name>Print debug messages</name>')
    xml_content.append('                <value>true</value>')
    xml_content.append('              </tick_box>')
    xml_content.append('              <target_box>')
    xml_content.append('                <name>Target</name>')
    xml_content.append('                <mode>Target_Box_Move_To_Original_Model</mode>')
    xml_content.append('                <tick_box>')
    xml_content.append('                  <name>Target - Replace existing data</name>')
    xml_content.append('                  <value>true</value>')
    xml_content.append('                </tick_box>')
    xml_content.append('              </target_box>')
    xml_content.append('              <run_button>')
    xml_content.append('                <name>Apply</name>')
    xml_content.append('              </run_button>')
    xml_content.append('            </panel>')
    xml_content.append('          </screen_layout>')
    xml_content.append('        </SLF_data>')
    xml_content.append('        <record_name>Apply Attribute Manipulator File</record_name>')
    xml_content.append('        <Parameter_Mappings>')
    xml_content.append('        </Parameter_Mappings>')
    xml_content.append('      </Run_option>')

    return xml_content