import os
import re
import pandas as pd
from docx import Document  # pip install python-docx

def extract_variable_AllChain(file_name):
    print('extract variable allchain file name = ', file_name)
    # Check if the file name ends with '.txt'
    if not file_name.endswith('Chain.txt'):
        # If not, return None
        print('returning out')
        return None

    # Extract the desired substring without '.txt' extension
    match = re.search(r'^(.*? Chain)\.txt$', file_name)
    print('match = ', match)
    if match:
        return match.group(1)
    else:
        return None
    
def save_plain_text(variable, paragraphs, output_folder):
    # Save plain text content to a file
    plain_text_content = ''
    for paragraph in paragraphs:
        plain_text_content += paragraph.text + '\n'

    output_file = os.path.join(output_folder, f'{variable}.chain')
    
    # Remove existing file if it exists (to ensure replacement)
    if os.path.exists(output_file):
        os.remove(output_file)
        print(f"Replaced existing file: {variable}.chain")
    
    with open(output_file, 'w') as file:
        file.write(plain_text_content)

def create_AllChain_file(output_folder, generated_files, project_folder=None):
    if project_folder is None:
        project_folder = os.path.abspath(os.path.join(output_folder, os.pardir))

    # Create the content for the AllChain file
    xml_content = []
    xml_content.append('<?xml version="1.0"?>')
    xml_content.append('<xml12d xmlns="http://www.12d.com/schema/xml12d-10.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" language="English" version="1.0" date="2024-01-15" time="08:16:59" xsi:schemaLocation="http://www.12d.com/schema/xml12d-10.0 http://www.12d.com/schema/xml12d-10.0/xml12d.xsd">')
    xml_content.append('  <meta_data>')
    xml_content.append('    <units>')
    xml_content.append('      <metric>')
    xml_content.append('        <linear>metre</linear>')
    xml_content.append('        <area>square metre</area>')
    xml_content.append('        <volume>cubic metre</volume>')
    xml_content.append('        <temperature>celsius</temperature>')
    xml_content.append('        <pressure>millibars</pressure>')
    xml_content.append('        <angular>decimal degrees</angular>')
    xml_content.append('        <direction>decimal degrees</direction>')
    xml_content.append('      </metric>')
    xml_content.append('    </units>')
    xml_content.append('    <application>')
    xml_content.append('      <name>12d Model</name>')
    xml_content.append('      <manufacturer>12d Solutions Pty Ltd</manufacturer>')
    xml_content.append('      <manufacturer_url>www.12d.com</manufacturer_url>')
    xml_content.append('      <application>12d Model 15.0C1j</application>')
    xml_content.append('      <application_build>15.1.10.22</application_build>')
    xml_content.append('      <application_path>C:\\Program Files\\12d\\12dmodel\\15.00\\nt.x64\\12d.exe</application_path>')
    xml_content.append('      <application_date_gmt>2023-06-16T00:33:18Z</application_date_gmt>')
    xml_content.append('      <application_date>2023-06-16T10:33:18</application_date>')
    xml_content.append('      <project_name>Rail</project_name>')
    xml_content.append('      <project_guid>{33C24EEB-4DA8-499f-B390-8960A7A2FF8D}</project_guid>')
    xml_content.append(f'      <project_folder>{project_folder}</project_folder>')
    xml_content.append('      <client>Kellogg Brown &amp; Root</client>')
    xml_content.append('      <dongle>ec514701fc</dongle>')
    xml_content.append('      <maintenance>active</maintenance>')
    xml_content.append('      <environment/>')
    xml_content.append('      <env4d>c:\\12d\\15.00\\user\\env.4d</env4d>')
    xml_content.append('      <user>K132177</user>')
    xml_content.append('      <export_file_name>ALL CHAIN.chain</export_file_name>')
    xml_content.append('      <export_date_gmt>2024-01-14T21:16:59Z</export_date_gmt>')
    xml_content.append('      <export_date>2024-01-15T08:16:59</export_date>')
    xml_content.append('    </application>')
    xml_content.append('  </meta_data>')
    xml_content.append('  <Chain>')
    xml_content.append('    <version>1</version>')
    xml_content.append('    <Settings>')
    xml_content.append('      <Parameter_File/>')
    xml_content.append('      <Prompt_for_parameters>false</Prompt_for_parameters>')
    xml_content.append('      <Always_record_for_parameters>false</Always_record_for_parameters>')
    xml_content.append('      <Interactive>false</Interactive>')
    xml_content.append('    </Settings>')
    xml_content.append('    <Commands>')

    for file_path in generated_files:
        file_name = os.path.basename(file_path)
        if file_name.endswith(".chain"):
            variable = os.path.splitext(file_name)[0]
            xml_content.append(create_chain_entry(variable))

    xml_content.append('      <Delete_all>')
    xml_content.append('        <Name>Delete all empty models</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <Mode>4</Mode>')
    xml_content.append('      </Delete_all>')
    xml_content.append('      <Prompt>')
    xml_content.append('        <Name>Prompt Chain Complete</Name>')
    xml_content.append('        <Active>true</Active>')
    xml_content.append('        <Continue_on_failure>false</Continue_on_failure>')
    xml_content.append('        <Uses_parameters>false</Uses_parameters>')
    xml_content.append('        <Interactive>false</Interactive>')
    xml_content.append('        <Comments>')
    xml_content.append('        </Comments>')
    xml_content.append('        <Title>Chain Result</Title>')
    xml_content.append('        <Parameter>Chain Result</Parameter>')
    xml_content.append('        <Prompt_Text>Chain Complete</Prompt_Text>')
    xml_content.append('        <Buttons>')
    xml_content.append('          <Button>')
    xml_content.append('            <Text>OK</Text>')
    xml_content.append('            <Value>OK</Value>')
    xml_content.append('          </Button>')
    xml_content.append('        </Buttons>')
    xml_content.append('        <Widgets>')
    xml_content.append('        </Widgets>')
    xml_content.append('      </Prompt>')
    xml_content.append('    </Commands>')
    xml_content.append('  </Chain>')
    xml_content.append('</xml12d>')
    
    output_file = os.path.join(output_folder, 'ALL Chain.chain')
    with open(output_file, 'w', encoding='utf-8') as file:
        file.write('\n'.join(xml_content))
    
    return output_file

def create_chain_entry(variable):
    content = (
        f'      <Chain>\n'
        f'        <Name>Recalc chain {variable}.chain</Name>\n'
        f'        <Active>true</Active>\n'
        f'        <Continue_on_failure>false</Continue_on_failure>\n'
        f'        <Uses_parameters>false</Uses_parameters>\n'
        f'        <Interactive>false</Interactive>\n'
        f'        <Comments></Comments>\n'
        f'        <Chain>{variable}.chain</Chain>\n'
        f'        <Chain_Parameters></Chain_Parameters>\n'
        f'      </Chain>'
    )
    return content

def create_shared_model(variable, discipline, prefix, description, object_dimension, file_ext):
    modified_variable = variable.replace('-', ' ')

    content = (
        f'      <Run_option>'
        f'        <Name>Create {discipline}/{prefix} {description} {object_dimension} {file_ext} Share model</Name>'
        f'        <Active>true</Active>'
        f'        <Continue_on_failure>false</Continue_on_failure>'
        f'        <Uses_parameters>false</Uses_parameters>'
        f'        <Interactive>false</Interactive>'
        f'        <Comments>'
        f'        </Comments>'
        f'        <SLF_data>'
        f'          <screen_layout>'
        f'            <version>1.0</version>'
        f'            <panel>'
        f'              <name>Change String Info</name>'
        f'              <x>313</x>'
        f'              <y>281</y>'
        f'              <resize>'
        f'                <width>1.26571429</width>'
        f'                <height>1</height>'
        f'              </resize>'
        f'              <source_box>'
        f'                <name>Data to convert</name>'
        f'                <mode>Source_Box_View</mode>'
        f'                <input_box>'
        f'                  <name>Data to convert - View</name>'
        f'                  <value>{modified_variable}</value>'
        f'                </input_box>'
        f'              </source_box>'
        f'              <input_box>'
        f'                <name>New name</name>'
        f'                <value />'
        f'              </input_box>'
        f'              <input_box>'
        f'                <name>New colour</name>'
        f'                <value />'
        f'              </input_box>'
        f'              <tick_box>'
        f'                <name>Clear individual segment colours</name>'
        f'                <value>false</value>'
        f'              </tick_box>'
        f'              <input_box>'
        f'                <name>New style</name>'
        f'                <value />'
        f'              </input_box>'
        f'              <tick_box>'
        f'                <name>Clear individual segment linestyles</name>'
        f'                <value>false</value>'
        f'              </tick_box>'
        f'              <input_box>'
        f'                <name>New pt-line type</name>'
        f'                <value>leave as is</value>'
        f'              </input_box>'
        f'              <input_box>'
        f'                <name>New weight</name>'
        f'                <value />'
        f'              </input_box>'
        f'              <target_box>'
        f'                <name>Target</name>'
        f'                <mode>Target_Box_Move_To_One_Model</mode>'
        f'                <input_box>'
        f'                  <name>Target - Move to model</name>'
    )

    if '-00-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext}</value>'
    elif '-01-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 01</value>'
    elif '-02-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 02</value>'
    elif '-03-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 03</value>'
    elif '-04-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 04</value>'
    elif '-05-' in variable:
        content += f'                  <value>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 05</value>'

    content += (
        f'                </input_box>'
        f'              </target_box>'
        f'              <run_button>'
        f'                <name>Change</name>'
        f'              </run_button>'
        f'            </panel>'
        f'          </screen_layout>'
        f'          '
        f'        </SLF_data>'
        f'        <Parameter_Mappings>'
        f'        </Parameter_Mappings>'
        f'      </Run_option>'
    )
    return content

def create_delete_shared_model(variable, discipline, prefix, description, object_dimension, file_ext):
    content = (
        f'      <Clean_model>'
        f'        <Name>Clean model {discipline}/{prefix} {description} {object_dimension} {file_ext}</Name>'
        f'        <Active>true</Active>'
        f'        <Continue_on_failure>true</Continue_on_failure>'
        f'        <Uses_parameters>false</Uses_parameters>'
        f'        <Interactive>false</Interactive>'
        f'        <Comments>'
        f'        </Comments>'
    )

    if '-00-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext}</Model_Name>'
    elif '-01-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 01</Model_Name>'
    elif '-02-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 02</Model_Name>'
    elif '-03-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 03</Model_Name>'
    elif '-04-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 04</Model_Name>'
    elif '-05-' in variable:
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext} Opt 05</Model_Name>'
    else:
        # Default case for filenames that don't match option patterns (e.g., -XX-)
        content += f'        <Model_Name>{discipline}/{prefix} {description} {object_dimension} {file_ext}</Model_Name>'

    content += (
        f'        <Model_ID>0</Model_ID>'
        f'        <Raster_Mode>0</Raster_Mode>'
        f'      </Clean_model>'
    )
    return content

def process_file(file_path, output_folder, project_folder, naming_data, model_type=None):
    """
    Process a file and generate chain file
    
    Args:
        model_type: "Model" for regular models, "TIN" for surface/triangulation models.
                   If None, auto-detects based on '-TR' in filename (for backward compatibility)
    """
    if not (file_path.lower().endswith('.dwg') or file_path.lower().endswith('.ifc')):
        return

    filename_stem = os.path.splitext(os.path.basename(file_path))[0]
    model_data = naming_data.loc[naming_data['filename'] == filename_stem]

    if model_data.empty:
        print(f"Skipping {filename_stem}: no matching entry in 'Model Naming.xlsx'")
        return

    row = model_data.iloc[0]
    discipline = row['discipline']
    prefix = row['prefix']
    description = row['description']
    object_dimension = str(row['object_dimension'])
    file_ext = str(row['file_ext'])

    variable = filename_stem 
    options_ext = ''
    surface_value = description
    modified_variable = variable.replace('-', ' ')

    if '-00-' in variable:
        options_ext = ''
    elif '-01-' in variable:
        options_ext = 'Opt 01'
    elif '-02-' in variable:
        options_ext = 'Opt 02'
    elif '-03-' in variable:
        options_ext = 'Opt 03'
    elif '-04-' in variable:
        options_ext = 'Opt 04'
    elif '-05-' in variable:
        options_ext = 'Opt 05'

    # Determine model type: use parameter if provided, otherwise auto-detect from filename
    if model_type is None:
        is_tin = '-TR' in variable
    else:
        is_tin = (model_type == "TIN")
    
    if is_tin:
        doc = Document()
        doc.add_paragraph(f'<?xml version="1.0"?>')
        doc.add_paragraph(f'<xml12d xmlns="http://www.12d.com/schema/xml12d-10.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" language="English" version="1.0" date="2024-01-16" time="20:57:27" xsi:schemaLocation="http://www.12d.com/schema/xml12d-10.0 http://www.12d.com/schema/xml12d-10.0/xml12d.xsd">')
        doc.add_paragraph(f'  <meta_data>')
        doc.add_paragraph(f'    <units>')
        doc.add_paragraph(f'      <metric>')
        doc.add_paragraph(f'        <linear>metre</linear>')
        doc.add_paragraph(f'        <area>square metre</area>')
        doc.add_paragraph(f'        <volume>cubic metre</volume>')
        doc.add_paragraph(f'        <temperature>celsius</temperature>')
        doc.add_paragraph(f'        <pressure>millibars</pressure>')
        doc.add_paragraph(f'        <angular>decimal degrees</angular>')
        doc.add_paragraph(f'        <direction>decimal degrees</direction>')
        doc.add_paragraph(f'      </metric>')
        doc.add_paragraph(f'    </units>')
        doc.add_paragraph(f'    <application>')
        doc.add_paragraph(f'      <name>12d Model</name>')
        doc.add_paragraph(f'      <manufacturer>12d Solutions Pty Ltd</manufacturer>')
        doc.add_paragraph(f'      <manufacturer_url>www.12d.com</manufacturer_url>')
        doc.add_paragraph(f'      <application>12d Model 15.0C1j</application>')
        doc.add_paragraph(f'      <application_build>15.1.10.22</application_build>')
        doc.add_paragraph(r'      <application_path>C:\Program Files\12d\12dmodel\15.00\nt.x64\12d.exe</application_path>')
        doc.add_paragraph(f'      <application_date_gmt>2023-06-16T00:33:18Z</application_date_gmt>')
        doc.add_paragraph(f'      <application_date>2023-06-16T10:33:18</application_date>')
        doc.add_paragraph(f'      <project_name>Project</project_name>')
        doc.add_paragraph(r'      <project_guid>{33C24EEB-4DA8-499f-B390-8960A7A2FF8D}</project_guid>')
        doc.add_paragraph(f'      <project_folder>{project_folder}</project_folder>')
        doc.add_paragraph(f'      <client>Kellogg Brown &amp; Root</client>')
        doc.add_paragraph(f'      <dongle>ec514701fc</dongle>')
        doc.add_paragraph(f'      <maintenance>active</maintenance>')
        doc.add_paragraph(f'      <environment/>')
        doc.add_paragraph(r'      <env4d>c:\12d\15.00\user\env.4d</env4d>')
        doc.add_paragraph(f'      <user>K132177</user>')
        doc.add_paragraph(f'      <export_file_name>{variable} Chain.chain</export_file_name>')
        doc.add_paragraph(f'      <export_date_gmt>2024-01-16T09:57:27Z</export_date_gmt>')
        doc.add_paragraph(f'      <export_date>2024-01-16T20:57:27</export_date>')
        doc.add_paragraph(f'    </application>')
        doc.add_paragraph(f'  </meta_data>')
        doc.add_paragraph(f'  <Chain>')
        doc.add_paragraph(f'    <version>1</version>')
        doc.add_paragraph(f'    <Settings>')
        doc.add_paragraph(f'      <Parameter_File/>')
        doc.add_paragraph(f'      <Prompt_for_parameters>false</Prompt_for_parameters>')
        doc.add_paragraph(f'      <Always_record_for_parameters>false</Always_record_for_parameters>')
        doc.add_paragraph(f'      <Interactive>false</Interactive>')
        doc.add_paragraph(f'    </Settings>')
        doc.add_paragraph(f'    <Commands>')
        doc.add_paragraph(f'      <Create_view>')
        doc.add_paragraph(f'        <Name>Create view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'        <View_Type>2010</View_Type>')
        doc.add_paragraph(f'        <View_Engine>GDI_legacy</View_Engine>')
        doc.add_paragraph(f'        <Favourite_File></Favourite_File>')
        doc.add_paragraph(f'        <Top>130</Top>')
        doc.add_paragraph(f'        <Left>120</Left>')
        doc.add_paragraph(f'        <Bot>640</Bot>')
        doc.add_paragraph(f'        <Right>790</Right>')
        doc.add_paragraph(f'        <Exaggeration></Exaggeration>')
        doc.add_paragraph(f'        <Use_Draw_Area>0</Use_Draw_Area>')
        doc.add_paragraph(f'        <Draw_Area_Width>-2147483648</Draw_Area_Width>')
        doc.add_paragraph(f'        <Draw_Area_Height>-2147483648</Draw_Area_Height>')
        doc.add_paragraph(f'      </Create_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model * from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Add_model_to_view>')
        doc.add_paragraph(f'        <Name>Add model {modified_variable}* to view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>{modified_variable}*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Add_model_to_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model *tin from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*tin</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Run_option>')
        doc.add_paragraph(f'        <Name>Delete models from view</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <SLF_data>')
        doc.add_paragraph(f'          <screen_layout>')
        doc.add_paragraph(f'            <version>1.0</version>')
        doc.add_paragraph(f'            <panel>')
        doc.add_paragraph(f'              <name>Delete</name>')
        doc.add_paragraph(f'              <x>241</x>')
        doc.add_paragraph(f'              <y>386</y>')
        doc.add_paragraph(f'              <source_box>')
        doc.add_paragraph(f'                <name>Data to delete</name>')
        doc.add_paragraph(f'                <mode>Source_Box_View</mode>')
        doc.add_paragraph(f'                <input_box>')
        doc.add_paragraph(f'                  <name>Data to delete - View</name>')
        doc.add_paragraph(f'                  <value>{modified_variable}</value>')
        doc.add_paragraph(f'                </input_box>')
        doc.add_paragraph(f'              </source_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Delete mode</name>')
        doc.add_paragraph(f'                <value>Split</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <target_box>')
        doc.add_paragraph(f'                <name>Target</name>')
        doc.add_paragraph(f'                <mode>Target_Box_Copy_To_One_Model</mode>')
        doc.add_paragraph(f'                <input_box>')
        doc.add_paragraph(f'                  <name>Target - Copy to model</name>')
        doc.add_paragraph(f'                  <value />')
        doc.add_paragraph(f'                </input_box>')
        doc.add_paragraph(f'              </target_box>')
        doc.add_paragraph(f'              <run_button>')
        doc.add_paragraph(f'                <name>Delete</name>')
        doc.add_paragraph(f'              </run_button>')
        doc.add_paragraph(f'            </panel>')
        doc.add_paragraph(f'          </screen_layout>')
        doc.add_paragraph(f'          ')
        doc.add_paragraph(f'        </SLF_data>')
        doc.add_paragraph(f'        <Parameter_Mappings>')
        doc.add_paragraph(f'        </Parameter_Mappings>')
        doc.add_paragraph(f'      </Run_option>')
        doc.add_paragraph(f'      <Run_option>')
        doc.add_paragraph(f'        <Name>Read {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <SLF_data>')
        doc.add_paragraph(f'          <screen_layout>')
        doc.add_paragraph(f'            <version>1.0</version>')
        doc.add_paragraph(f'            <panel>')
        doc.add_paragraph(f'              <name>Read DWG/DXF Data</name>')
        doc.add_paragraph(f'              <x>194</x>')
        doc.add_paragraph(f'              <y>205</y>')
        doc.add_paragraph(f'              <resize>')
        doc.add_paragraph(f'                <width>2.19732441</width>')
        doc.add_paragraph(f'                <height>1</height>')
        doc.add_paragraph(f'              </resize>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Create anonymous function</name>')
        doc.add_paragraph(f'                <value>false</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Import method</name>')
        doc.add_paragraph(f'                <value />')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <file_box>')
        doc.add_paragraph(f'                <name>File</name>')
        doc.add_paragraph(f'                <value>{file_path}</value>')
        doc.add_paragraph(f'              </file_box>')
        doc.add_paragraph(f'              <file_box>')
        doc.add_paragraph(f'                <name>Map file</name>')
        doc.add_paragraph(f'                <value />')
        doc.add_paragraph(f'              </file_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Pre*postfix for models</name>')
        doc.add_paragraph(f'                <value>{modified_variable}/*</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Allow merge into existing models</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Target layer</name>')
        doc.add_paragraph(f'                <value />')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Null level value</name>')
        doc.add_paragraph(f'                <value>0</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Default lineweight</name>')
        doc.add_paragraph(f'                <value>0.25</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Spline approximation</name>')
        doc.add_paragraph(f'                <value>12</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Names</name>')
        doc.add_paragraph(f'                <value>layer for name</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Images</name>')
        doc.add_paragraph(f'                <value>ignore</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Blocks</name>')
        doc.add_paragraph(f'                <value>to symbols</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Block attributes</name>')
        doc.add_paragraph(f'                <value>ignore</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Only create visible symbols</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Translate 3DFaces to Faces</name>')
        doc.add_paragraph(f'                <value>false</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Use 12d Acad colour numbers</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Create 2d/3d polys from ctrl points</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Head to tail points/lines</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Only load visible layers</name>')
        doc.add_paragraph(f'                <value>true</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Load paper space</name>')
        doc.add_paragraph(f'                <value>false</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <tick_box>')
        doc.add_paragraph(f'                <name>Load xref files</name>')
        doc.add_paragraph(f'                <value>false</value>')
        doc.add_paragraph(f'              </tick_box>')
        doc.add_paragraph(f'              <run_button>')
        doc.add_paragraph(f'                <name>&amp;Read</name>')
        doc.add_paragraph(f'              </run_button>')
        doc.add_paragraph(f'            </panel>')
        doc.add_paragraph(f'          </screen_layout>')
        doc.add_paragraph(f'          ')
        doc.add_paragraph(f'        </SLF_data>')
        doc.add_paragraph(f'        <Parameter_Mappings>')
        doc.add_paragraph(f'        </Parameter_Mappings>')
        doc.add_paragraph(f'      </Run_option>')
        doc.add_paragraph(f'      <Add_model_to_view>')
        doc.add_paragraph(f'        <Name>Add model {modified_variable}* to view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>{modified_variable}*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Add_model_to_view>')
        doc.add_paragraph(f'      <If_function_exists>')
        doc.add_paragraph(f'        <Name>If function {modified_variable} tin Exists</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Conditional>')
        doc.add_paragraph(f'          <Pass_Mode>1</Pass_Mode>')
        doc.add_paragraph(f'          <Pass_Action>run tin function</Pass_Action>')
        doc.add_paragraph(f'          <Fail_Mode>0</Fail_Mode>')
        doc.add_paragraph(f'          <Fail_Action/>')
        doc.add_paragraph(f'        </Conditional>')
        doc.add_paragraph(f'        <Function>{modified_variable} tin</Function>')
        doc.add_paragraph(f'      </If_function_exists>')
        doc.add_paragraph(f'      <Label>')
        doc.add_paragraph(f'        <Name>create new tin</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'      </Label>')
        doc.add_paragraph(f'      <Manual_option>')
        doc.add_paragraph(f'        <Name>Option Triangulate a Data Source - Manual</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Panel_Data><screen_layout>')
        doc.add_paragraph(f'  <version>1.0</version>')
        doc.add_paragraph(f'  <panel>')
        doc.add_paragraph(f'    <name>Triangulate a Data Source</name>')
        doc.add_paragraph(f'    <x>458</x>')
        doc.add_paragraph(f'    <y>287</y>')
        doc.add_paragraph(f'    <widget_pages>')
        doc.add_paragraph(f'      <name>Tabs</name>')
        doc.add_paragraph(f'      <current_page>General</current_page>')
        doc.add_paragraph(f'      <widget_page>')
        doc.add_paragraph(f'        <name>General</name>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Retriangulate function</name>')
        doc.add_paragraph(f'          <value>{modified_variable} tin</value>')
        doc.add_paragraph(f'        </input_box>')
                        # FIX NAME VALUE
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>New tin name</name>')
        doc.add_paragraph(f'          <value>tin {prefix} {surface_value} {file_ext} {options_ext}</value>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Tin colour</name>')
        doc.add_paragraph(f'          <value>vis granular2</value>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Tin style</name>')
        doc.add_paragraph(f'          <value>1</value>')
        doc.add_paragraph(f'        </input_box>')
                        # FIX NAME VALUE
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Model for tin</name>')
        doc.add_paragraph(f'          <value>tin/{prefix} {surface_value} {file_ext} {options_ext}</value>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Preserve strings</name>')
        doc.add_paragraph(f'          <value>true</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Weed tin</name>')
        doc.add_paragraph(f'          <value>false</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Cell method</name>')
        doc.add_paragraph(f'          <value>true</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Remove bubbles</name>')
        doc.add_paragraph(f'          <value>false</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Triangle data</name>')
        doc.add_paragraph(f'          <value>false</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Colour by triangle data</name>')
        doc.add_paragraph(f'          <value>false</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Create many</name>')
        doc.add_paragraph(f'          <value>false</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'      </widget_page>')
        doc.add_paragraph(f'      <widget_page>')
        doc.add_paragraph(f'        <name>Data</name>')
        doc.add_paragraph(f'        <source_box>')
        doc.add_paragraph(f'          <name>Data to triangulate</name>')
        doc.add_paragraph(f'          <mode>Source_Box_View</mode>')
        doc.add_paragraph(f'          <input_box>')
        doc.add_paragraph(f'            <name>Data to triangulate - View</name>')
        doc.add_paragraph(f'            <value>{modified_variable}</value>')
        doc.add_paragraph(f'          </input_box>')
        doc.add_paragraph(f'        </source_box>')
        doc.add_paragraph(f'        <polygon_box>')
        doc.add_paragraph(f'          <name>Data polygon</name>')
        doc.add_paragraph(f'        </polygon_box>')
        doc.add_paragraph(f'      </widget_page>')
        doc.add_paragraph(f'      <widget_page>')
        doc.add_paragraph(f'        <name>Nulling</name>')
        doc.add_paragraph(f'        <tick_box>')
        doc.add_paragraph(f'          <name>Apply nulling</name>')
        doc.add_paragraph(f'          <value>true</value>')
        doc.add_paragraph(f'        </tick_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Angle</name>')
        doc.add_paragraph(f'          <value>5</value>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Length</name>')
        doc.add_paragraph(f'          <value>5</value>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Combined angle</name>')
        doc.add_paragraph(f'          <value/>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <input_box>')
        doc.add_paragraph(f'          <name>Combined length</name>')
        doc.add_paragraph(f'          <value/>')
        doc.add_paragraph(f'        </input_box>')
        doc.add_paragraph(f'        <polygon_box>')
        doc.add_paragraph(f'          <name>Null polygon</name>')
        doc.add_paragraph(f'        </polygon_box>')
        doc.add_paragraph(f'      </widget_page>')
        doc.add_paragraph(f'    </widget_pages>')
        doc.add_paragraph(f'    <run_button>')
        doc.add_paragraph(f'      <name>Triangulate</name>')
        doc.add_paragraph(f'    </run_button>')
        doc.add_paragraph(f'  </panel>')
        doc.add_paragraph(f'</screen_layout></Panel_Data>')
        doc.add_paragraph(f'        <Panel_Name>Triangulate a Data Source</Panel_Name>')
        doc.add_paragraph(f'        <Clean_Up>1</Clean_Up>')
        doc.add_paragraph(f'        <Buttons>')
        doc.add_paragraph(f'          <Button>')
        doc.add_paragraph(f'            <Name>Triangulate</Name>')
        doc.add_paragraph(f'            <Order>0</Order>')
        doc.add_paragraph(f'          </Button>')
        doc.add_paragraph(f'        </Buttons>')
        doc.add_paragraph(f'        <Parameter_Mappings>')
        doc.add_paragraph(f'        </Parameter_Mappings>')
        doc.add_paragraph(f'      </Manual_option>')
        doc.add_paragraph(f'      <Label>')
        doc.add_paragraph(f'        <Name>run tin function</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'      </Label>')
        doc.add_paragraph(f'      <Function>')
        doc.add_paragraph(f'        <Name>Recalc {modified_variable} tin</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Function>{modified_variable} tin</Function>')
        doc.add_paragraph(f'      </Function>')
        doc.add_paragraph(f'    </Commands>')
        doc.add_paragraph(f'  </Chain>')
        doc.add_paragraph(f'</xml12d>')

    else:
        doc = Document()
        doc.add_paragraph(f'<?xml version="1.0"?>')
        doc.add_paragraph(f'<xml12d xmlns="http://www.12d.com/schema/xml12d-10.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" language="English" version="1.0" date="2023-10-13" time="08:35:06" xsi:schemaLocation="http://www.12d.com/schema/xml12d-10.0 http://www.12d.com/schema/xml12d-10.0/xml12d.xsd">')
        doc.add_paragraph(f'  <meta_data>')
        doc.add_paragraph(f'    <units>')
        doc.add_paragraph(f'      <metric>')
        doc.add_paragraph(f'        <linear>metre</linear>')
        doc.add_paragraph(f'        <area>square metre</area>')
        doc.add_paragraph(f'        <volume>cubic metre</volume>')
        doc.add_paragraph(f'        <temperature>celsius</temperature>')
        doc.add_paragraph(f'        <pressure>millibars</pressure>')
        doc.add_paragraph(f'        <angular>decimal degrees</angular>')
        doc.add_paragraph(f'        <direction>decimal degrees</direction>')
        doc.add_paragraph(f'      </metric>')
        doc.add_paragraph(f'    </units>')
        doc.add_paragraph(f'    <application>')
        doc.add_paragraph(f'      <name>12d Model</name>')
        doc.add_paragraph(f'      <manufacturer>12d Solutions Pty Ltd</manufacturer>')
        doc.add_paragraph(f'      <manufacturer_url>www.12d.com</manufacturer_url>')
        doc.add_paragraph(f'      <application>12d Model 15.0C1j</application>')
        doc.add_paragraph(f'      <application_build>15.1.10.22</application_build>')
        doc.add_paragraph(r'      <application_path>C:\Program Files\12d\12dmodel\15.00\nt.x64\12d.exe</application_path>')
        doc.add_paragraph(f'      <application_date_gmt>2023-06-16T00:33:18Z</application_date_gmt>')
        doc.add_paragraph(f'      <application_date>2023-06-16T10:33:18</application_date>')
        doc.add_paragraph(f'      <project_name>Master</project_name>')
        doc.add_paragraph(r'      <project_guid>{33C24EEB-4DA8-499f-B390-8960A7A2FF8D}</project_guid>')
        doc.add_paragraph(f'      <project_folder>{project_folder}</project_folder>')
        doc.add_paragraph(f'      <client>Kellogg Brown &amp; Root</client>')
        doc.add_paragraph(f'      <dongle>ec514701fc</dongle>')
        doc.add_paragraph(f'      <maintenance>active</maintenance>')
        doc.add_paragraph(f'      <environment/>')
        doc.add_paragraph(r'      <env4d>c:\12d\15.00\user\env.4d</env4d>')
        doc.add_paragraph(f'      <user>K132177</user>')
        doc.add_paragraph(f'      <export_file_name>{variable} Chain.chain</export_file_name>')
        doc.add_paragraph(f'      <export_date_gmt>2023-10-12T21:35:06Z</export_date_gmt>')
        doc.add_paragraph(f'      <export_date>2023-10-13T08:35:06</export_date>')
        doc.add_paragraph(f'    </application>')
        doc.add_paragraph(f'  </meta_data>')
        doc.add_paragraph(f'  <Chain>')
        doc.add_paragraph(f'    <version>1</version>')
        doc.add_paragraph(f'    <Settings>')
        doc.add_paragraph(f'      <Parameter_File/>')
        doc.add_paragraph(f'      <Prompt_for_parameters>false</Prompt_for_parameters>')
        doc.add_paragraph(f'      <Always_record_for_parameters>false</Always_record_for_parameters>')
        doc.add_paragraph(f'      <Interactive>false</Interactive>')
        doc.add_paragraph(f'    </Settings>')
        doc.add_paragraph(f'    <Commands>')
        doc.add_paragraph(create_delete_shared_model(variable, discipline, prefix, description, object_dimension, file_ext))
        doc.add_paragraph(f'      <Create_view>')
        doc.add_paragraph(f'        <Name>Create view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'        <View_Type>2010</View_Type>')
        doc.add_paragraph(f'        <View_Engine>GDI_legacy</View_Engine>')
        doc.add_paragraph(f'        <Favourite_File></Favourite_File>')
        doc.add_paragraph(f'        <Top>40</Top>')
        doc.add_paragraph(f'        <Left>30</Left>')
        doc.add_paragraph(f'        <Bot>565</Bot>')
        doc.add_paragraph(f'        <Right>715</Right>')
        doc.add_paragraph(f'        <Exaggeration></Exaggeration>')
        doc.add_paragraph(f'        <Use_Draw_Area>0</Use_Draw_Area>')
        doc.add_paragraph(f'        <Draw_Area_Width>-2147483648</Draw_Area_Width>')
        doc.add_paragraph(f'        <Draw_Area_Height>-2147483648</Draw_Area_Height>')
        doc.add_paragraph(f'      </Create_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model * from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Add_model_to_view>')
        doc.add_paragraph(f'        <Name>Add model {modified_variable}* to view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>{modified_variable}*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Add_model_to_view>')
        doc.add_paragraph(f'      <Run_option>')
        doc.add_paragraph(f'        <Name>Delete models from view</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <SLF_data>')
        doc.add_paragraph(f'          <screen_layout>')
        doc.add_paragraph(f'            <version>1.0</version>')
        doc.add_paragraph(f'            <panel>')
        doc.add_paragraph(f'              <name>Delete</name>')
        doc.add_paragraph(f'              <x>497</x>')
        doc.add_paragraph(f'              <y>319</y>')
        doc.add_paragraph(f'              <source_box>')
        doc.add_paragraph(f'                <name>Data to delete</name>')
        doc.add_paragraph(f'                <mode>Source_Box_View</mode>')
        doc.add_paragraph(f'                <input_box>')
        doc.add_paragraph(f'                  <name>Data to delete - View</name>')
        doc.add_paragraph(f'                  <value>{modified_variable}</value>')
        doc.add_paragraph(f'                </input_box>')
        doc.add_paragraph(f'              </source_box>')
        doc.add_paragraph(f'              <input_box>')
        doc.add_paragraph(f'                <name>Delete mode</name>')
        doc.add_paragraph(f'                <value>Split</value>')
        doc.add_paragraph(f'              </input_box>')
        doc.add_paragraph(f'              <target_box>')
        doc.add_paragraph(f'                <name>Target</name>')
        doc.add_paragraph(f'                <mode>Target_Box_Copy_To_One_Model</mode>')
        doc.add_paragraph(f'                <input_box>')
        doc.add_paragraph(f'                  <name>Target - Copy to model</name>')
        doc.add_paragraph(f'                  <value/>')
        doc.add_paragraph(f'                </input_box>')
        doc.add_paragraph(f'              </target_box>')
        doc.add_paragraph(f'              <run_button>')
        doc.add_paragraph(f'                <name>Delete</name>')
        doc.add_paragraph(f'              </run_button>')
        doc.add_paragraph(f'            </panel>')
        doc.add_paragraph(f'          </screen_layout>')
        doc.add_paragraph(f'        </SLF_data>')
        doc.add_paragraph(f'        <Parameter_Mappings>')
        doc.add_paragraph(f'        </Parameter_Mappings>')
        doc.add_paragraph(f'      </Run_option>')

        # ---------- IMPORT IFC FILE ---------- #
        if file_path.lower().endswith('.ifc'):
            doc.add_paragraph(f'<Run_option>')
            doc.add_paragraph(f'    <Name>IFC Express Reader</Name>')
            doc.add_paragraph(f'    <Active>true</Active>')
            doc.add_paragraph(f'    <Continue_on_failure>false</Continue_on_failure>')
            doc.add_paragraph(f'    <Uses_parameters>false</Uses_parameters>')
            doc.add_paragraph(f'    <Interactive>false</Interactive>')
            doc.add_paragraph(f'    <Comments>')
            doc.add_paragraph(f'    <Comment>import {modified_variable}</Comment>')
            doc.add_paragraph(f'    </Comments>')
            doc.add_paragraph(f'    <SLF_data>')
            doc.add_paragraph(f'    <screen_layout>')
            doc.add_paragraph(f'        <version>1.0</version>')
            doc.add_paragraph(f'        <panel>')
            doc.add_paragraph(f'        <name>IFC Express Reader</name>')
            doc.add_paragraph(f'        <x>159</x>')
            doc.add_paragraph(f'        <y>352</y>')
            doc.add_paragraph(f'        <resize>')
            doc.add_paragraph(f'            <width>1.87936508</width>')
            doc.add_paragraph(f'            <height>1</height>')
            doc.add_paragraph(f'        </resize>')
            doc.add_paragraph(f'        <widget_pages>')
            doc.add_paragraph(f'            <name>Tab box</name>')
            doc.add_paragraph(f'            <current_page>General</current_page>')
            doc.add_paragraph(f'            <widget_page>')
            doc.add_paragraph(f'            <name>General</name>')
            doc.add_paragraph(f'            <files_box>')
            doc.add_paragraph(f'                <name>Input file</name>')
            doc.add_paragraph(f'                <tick_box>')
            doc.add_paragraph(f'                <name>Advanced</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'                </tick_box>')
            doc.add_paragraph(f'                <widget_pages>')
            doc.add_paragraph(f'                <name>Pages</name>')
            doc.add_paragraph(f'                <current_page>1</current_page>')
            doc.add_paragraph(f'                <widget_page>')
            doc.add_paragraph(f'                    <name>1</name>')
            doc.add_paragraph(f'                    <file_box>')
            doc.add_paragraph(f'                    <name>File to read</name>')
            doc.add_paragraph(f'                    <value>{file_path}</value>')
            doc.add_paragraph(f'                    </file_box>')
            doc.add_paragraph(f'                </widget_page>')
            doc.add_paragraph(f'                </widget_pages>')
            doc.add_paragraph(f'            </files_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Model</name>')
            doc.add_paragraph(f'                <value>{modified_variable} ifc</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Pre*postfix for models</name>')
            doc.add_paragraph(f'                <value>{modified_variable}/*</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Split data into Entity models?</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Presentation Layer as model</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Use pre*postfix for tins</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Clean model?</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Apply map coordinates</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Use reference trimeshes</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Save ifc file in memory?</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Null level value</name>')
            doc.add_paragraph(f'                <value>0</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Make string name</name>')
            doc.add_paragraph(f'                <value>Instance name</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Pit pipe mode</name>')
            doc.add_paragraph(f'                <value>Trimeshes</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Default colour</name>')
            doc.add_paragraph(f'                <value>cyan</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Save GlobalId as Attribute?</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>GlobalId attribute path</name>')
            doc.add_paragraph(f'                <value>IfcGlobalId</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Save Element Type as Attribute?</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Element Type attribute path</name>')
            doc.add_paragraph(f'                <value>IfcEntity</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            </widget_page>')
            doc.add_paragraph(f'            <widget_page>')
            doc.add_paragraph(f'            <name>Alignment</name>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Reverse calc parts</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <tick_box>')
            doc.add_paragraph(f'                <name>Copy alignment</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'            </tick_box>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Label style</name>')
            doc.add_paragraph(f'                <value>default</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            </widget_page>')
            doc.add_paragraph(f'            <widget_page>')
            doc.add_paragraph(f'            <name>Unit</name>')
            doc.add_paragraph(f'            <input_box>')
            doc.add_paragraph(f'                <name>Convert length unit to</name>')
            doc.add_paragraph(f'                <value>METRE</value>')
            doc.add_paragraph(f'            </input_box>')
            doc.add_paragraph(f'            </widget_page>')
            doc.add_paragraph(f'        </widget_pages>')
            doc.add_paragraph(f'        <run_button>')
            doc.add_paragraph(f'            <name>Read</name>')
            doc.add_paragraph(f'        </run_button>')
            doc.add_paragraph(f'        </panel>')
            doc.add_paragraph(f'    </screen_layout>')
            doc.add_paragraph(f'    </SLF_data>')
            doc.add_paragraph(f'    <Parameter_Mappings>')
            doc.add_paragraph(f'    </Parameter_Mappings>')
            doc.add_paragraph(f'</Run_option>')

        # ---------- IMPORT DWG FILE ---------- #
        elif file_path.lower().endswith('.dwg'):
            doc.add_paragraph(f'      <Run_option>')
            doc.add_paragraph(f'        <Name>Read DWG/DXF Data</Name>')
            doc.add_paragraph(f'        <Active>true</Active>')
            doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
            doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
            doc.add_paragraph(f'        <Interactive>false</Interactive>')
            doc.add_paragraph(f'        <Comments>')
            doc.add_paragraph(f'        </Comments>')
            doc.add_paragraph(f'        <SLF_data>')
            doc.add_paragraph(f'          <screen_layout>')
            doc.add_paragraph(f'            <version>1.0</version>')
            doc.add_paragraph(f'            <panel>')
            doc.add_paragraph(f'              <name>Read DWG/DXF Data</name>')
            doc.add_paragraph(f'              <x>138</x>')
            doc.add_paragraph(f'              <y>208</y>')
            doc.add_paragraph(f'              <resize>')
            doc.add_paragraph(f'                <width>2.0735786</width>')
            doc.add_paragraph(f'                <height>1</height>')
            doc.add_paragraph(f'              </resize>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Create anonymous function</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Import method</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <file_box>')
            doc.add_paragraph(f'                <name>File</name>')
            doc.add_paragraph(f'                <value>{file_path}</value>')
            doc.add_paragraph(f'              </file_box>')
            doc.add_paragraph(f'              <file_box>')
            doc.add_paragraph(f'                <name>Map file</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </file_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Pre*postfix for models</name>')
            doc.add_paragraph(f'                <value>{modified_variable}/*</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Allow merge into existing models</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Target layer</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Null level value</name>')
            doc.add_paragraph(f'                <value>0</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Default lineweight</name>')
            doc.add_paragraph(f'                <value>0.25</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Spline approximation</name>')
            doc.add_paragraph(f'                <value>12</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Names</name>')
            doc.add_paragraph(f'                <value>layer for name</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Images</name>')
            doc.add_paragraph(f'                <value>ignore</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Blocks</name>')
            doc.add_paragraph(f'                <value>to symbols</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Block attributes</name>')
            doc.add_paragraph(f'                <value>ignore</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Only create visible symbols</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Translate 3DFaces to Faces</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Use 12d Acad colour numbers</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Create 2d/3d polys from ctrl points</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Head to tail points/lines</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Only load visible layers</name>')
            doc.add_paragraph(f'                <value>true</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Load paper space</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Load xref files</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <run_button>')
            doc.add_paragraph(f'                <name>&amp;Read</name>')
            doc.add_paragraph(f'              </run_button>')
            doc.add_paragraph(f'            </panel>')
            doc.add_paragraph(f'          </screen_layout>')
            doc.add_paragraph(f'        </SLF_data>')
            doc.add_paragraph(f'        <Parameter_Mappings>')
            doc.add_paragraph(f'        </Parameter_Mappings>')
            doc.add_paragraph(f'      </Run_option>')

                # ---------- IMPORT DGN FILE ---------- #
        elif file_path.lower().endswith('.dgn'):
            doc.add_paragraph(f'      <Run_option>')
            doc.add_paragraph(f'        <Name>Read DGN File</Name>')
            doc.add_paragraph(f'        <Active>true</Active>')
            doc.add_paragraph(f'        <Continue_on_failure>false</Continue_on_failure>')
            doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
            doc.add_paragraph(f'        <Interactive>false</Interactive>')
            doc.add_paragraph(f'        <Comments>')
            doc.add_paragraph(f'        </Comments>')
            doc.add_paragraph(f'        <SLF_data>')
            doc.add_paragraph(f'          <screen_layout>')
            doc.add_paragraph(f'            <version>1.0</version>')
            doc.add_paragraph(f'            <panel>')
            doc.add_paragraph(f'              <name>Read DGN external v78</name>')
            doc.add_paragraph(f'              <x>303</x>')
            doc.add_paragraph(f'              <y>312</y>')
            doc.add_paragraph(f'              <resize>')
            doc.add_paragraph(f'                <width>1.4115942</width>')
            doc.add_paragraph(f'                <height>1</height>')
            doc.add_paragraph(f'              </resize>')
            doc.add_paragraph(f'              <tick_box>')
            doc.add_paragraph(f'                <name>Create anonymous function</name>')
            doc.add_paragraph(f'                <value>false</value>')
            doc.add_paragraph(f'              </tick_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Import method</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <file_box>')
            doc.add_paragraph(f'                <name>File</name>')
            doc.add_paragraph(f'                <directory>{file_path}</directory>')
            doc.add_paragraph(f'                <value>{file_path}\{modified_variable}</value>')
            doc.add_paragraph(f'              </file_box>')
            doc.add_paragraph(f'              <file_box>')
            doc.add_paragraph(f'                <name>Mapfile</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </file_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Mapfile key</name>')
            doc.add_paragraph(f'                <value/>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Pre*postfix for models</name>')
            doc.add_paragraph(f'                <value>{modified_variable}/*</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Allow merge into existing models</name>')
            doc.add_paragraph(f'                <value>yes</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Level name as model</name>')
            doc.add_paragraph(f'                <value>yes</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Hidden levels</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Frozen levels</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Invisible elements</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Combine elements</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Shapes as faces</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Text as super strings</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Create symbols</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <input_box>')
            doc.add_paragraph(f'                <name>Load xref files</name>')
            doc.add_paragraph(f'                <value>no</value>')
            doc.add_paragraph(f'              </input_box>')
            doc.add_paragraph(f'              <run_button>')
            doc.add_paragraph(f'                <name>&amp;Read</name>')
            doc.add_paragraph(f'              </run_button>')
            doc.add_paragraph(f'            </panel>')
            doc.add_paragraph(f'          </screen_layout>')
            doc.add_paragraph(f'        </SLF_data>')
            doc.add_paragraph(f'        <record_name>Read DGN File</record_name>')
            doc.add_paragraph(f'        <Parameter_Mappings>')
            doc.add_paragraph(f'        </Parameter_Mappings>')
            doc.add_paragraph(f'      </Run_option>')

        doc.add_paragraph(f'      <Add_model_to_view>')
        doc.add_paragraph(f'        <Name>Add model {modified_variable}* to view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>{modified_variable}*</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Add_model_to_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model *tm from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*tm</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model *tin from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*tin</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model *Label from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*Label</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(f'      <Remove_model_from_view>')
        doc.add_paragraph(f'        <Name>Remove model *Mark from view {modified_variable}</Name>')
        doc.add_paragraph(f'        <Active>true</Active>')
        doc.add_paragraph(f'        <Continue_on_failure>true</Continue_on_failure>')
        doc.add_paragraph(f'        <Uses_parameters>false</Uses_parameters>')
        doc.add_paragraph(f'        <Interactive>false</Interactive>')
        doc.add_paragraph(f'        <Comments>')
        doc.add_paragraph(f'        </Comments>')
        doc.add_paragraph(f'        <Model>*Mark</Model>')
        doc.add_paragraph(f'        <View>{modified_variable}</View>')
        doc.add_paragraph(f'      </Remove_model_from_view>')
        doc.add_paragraph(create_shared_model(variable, discipline, prefix, description, object_dimension, file_ext))
        doc.add_paragraph(f'    </Commands>')
        doc.add_paragraph(f'  </Chain>')
        doc.add_paragraph(f'</xml12d>')

    # Step 4: Save plain text content to a file
    save_plain_text(variable, doc.paragraphs, output_folder) 