"""
Generate Convert Lines to Variable command
"""
from typing import List


def convert_lines_to_variable_command(prefix: str) -> List[str]:
    """
    Generate Change Super String Height XML command
    
    Args:
        prefix: Prefix for the model filter
    
    Returns:
        List of XML lines for Convert Lines to Variable command
    """
    return [
        '      <Run_option>',
        '        <Name>Change Super String Height</Name>',
        '        <Active>true</Active>',
        '        <Continue_on_failure>false</Continue_on_failure>',
        '        <Uses_parameters>false</Uses_parameters>',
        '        <Interactive>false</Interactive>',
        '        <Comments>',
        '        </Comments>',
        '        <SLF_data>',
        '          <screen_layout>',
        '            <version>1.0</version>',
        '            <panel>',
        '              <name>Change Super String Height</name>',
        '              <x>2014</x>',
        '              <y>348</y>',
        '              <source_box>',
        '                <name>Data to change</name>',
        '                <mode>Source_Box_Filter</mode>',
        '                <widget_pages>',
        '                  <name>Data to change - Groups</name>',
        '                  <current_page>Model</current_page>',
        '                  <widget_page>',
        '                    <name>View</name>',
        '                    <input_box>',
        '                      <name>Data to change - View Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model</name>',
        '                    <input_box>',
        '                      <name>Data to change - Model Name</name>',
        f'                      <value>{prefix}/*</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Model ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Model ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Models</name>',
        '                    <grid_box>',
        '                      <name>Models</name>',
        '                      <columns>',
        '                        <column>Model</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>String Info</name>',
        '                    <input_box>',
        '                      <name>Data to change - String Type</name>',
        '                      <value>any string</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - String Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - String Colour</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - String Breakline</name>',
        '                      <value>any string</value>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - String Linestyle</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - String Weight</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Point ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to change - Point ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Point ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Polygons</name>',
        '                    <input_box>',
        '                      <name>Data to change - Fence Mode</name>',
        '                      <value>String inside</value>',
        '                    </input_box>',
        '                    <polygon_box>',
        '                      <name>Data to change - Fence Polygon</name>',
        '                    </polygon_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Extents</name>',
        '                    <input_box>',
        '                      <name>Data to change - Element X Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Y Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Z Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element X Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Y Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Z Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Plan length</name>',
        '                    <input_box>',
        '                      <name>Data to change - Plan Length Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Plan Length Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>ID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to change - Element ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Function</name>',
        '                    <input_box>',
        '                      <name>Data to change - Function Name</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Function ID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Function ID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Time</name>',
        '                    <input_box>',
        '                      <name>Data to change - Element Create Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Create Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Update Time Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Element Update Time Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Model Attributes</name>',
        '                    <grid_box>',
        '                      <name>Model Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Element Attributes</name>',
        '                    <grid_box>',
        '                      <name>Element Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Attributes</name>',
        '                    <grid_box>',
        '                      <name>Vertex Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment Attributes</name>',
        '                    <grid_box>',
        '                      <name>Segment Attributes</name>',
        '                      <columns>',
        '                        <column>Name</column>',
        '                        <column>Type</column>',
        '                        <column>Data</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex Count</name>',
        '                    <input_box>',
        '                      <name>Data to change - Vertex Count Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Vertex Count Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Tags</name>',
        '                    <input_box>',
        '                      <name>Tag</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Search mode</name>',
        '                      <value>String and models tags</value>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Name masks</name>',
        '                    <grid_box>',
        '                      <name>Name mask filter</name>',
        '                      <columns>',
        '                        <column>Active?</column>',
        '                        <column>Not?</column>',
        '                        <column>Name Mask</column>',
        '                      </columns>',
        '                      <data>',
        '                      </data>',
        '                    </grid_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Vertex UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to change - Vertex UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Vertex UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                  <widget_page>',
        '                    <name>Segment UID&apos;s</name>',
        '                    <input_box>',
        '                      <name>Data to change - Segment UID Minimum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                    <input_box>',
        '                      <name>Data to change - Segment UID Maximum</name>',
        '                      <value/>',
        '                    </input_box>',
        '                  </widget_page>',
        '                </widget_pages>',
        '                <tick_box>',
        '                  <name>Use log lines</name>',
        '                  <value>false</value>',
        '                </tick_box>',
        '              </source_box>',
        '              <input_box>',
        '                <name>Action</name>',
        '                <value>set</value>',
        '              </input_box>',
        '              <input_box>',
        '                <name>Apply</name>',
        '                <value>variable</value>',
        '              </input_box>',
        '              <input_box>',
        '                <name>Height</name>',
        '                <value>10</value>',
        '              </input_box>',
        '              <target_box>',
        '                <name>Target</name>',
        '                <mode>Target_Box_Move_To_Original_Model</mode>',
        '                <tick_box>',
        '                  <name>Target - Replace existing data</name>',
        '                  <value>true</value>',
        '                </tick_box>',
        '              </target_box>',
        '              <run_button>',
        '                <name>Change</name>',
        '              </run_button>',
        '            </panel>',
        '          </screen_layout>',
        '        </SLF_data>',
        '        <Parameter_Mappings>',
        '        </Parameter_Mappings>',
        '      </Run_option>'
    ]
